apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hieuonprem-ingress
spec:
  rules:
  - host: kubeconapim.168.63.236.59.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: hieuonprem
          servicePort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: hieuonprem-token
type: Opaque
stringData:
  value: "GatewayKey hieuonprem&202001071320&WaQvPACiLnsjfjMEZVv8UH8uDpfyfO3LGswVtX9dJYF1cFFsjCL1g2tJC8vNNkveM9gDonXINLA4kS4ugsCu5w=="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hieuonprem
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hieuonprem
  template:
    metadata:
      labels:
        app: hieuonprem
    spec:
      dnsPolicy: Default
      containers:
      - name: hieuonprem
        image: mcr.microsoft.com/azure-api-management/gateway:alpha
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: config.service.endpoint
          value: "https://hieu.management.azure-api.net/subscriptions/122b8000-f910-48c4-899a-845d36600f10/resourceGroups/feedback/providers/Microsoft.ApiManagement/service/hieu?api-version=2018-06-01-preview"
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: hieuonprem-token
              key: value
---
apiVersion: v1
kind: Service
metadata:
  name: hieuonprem
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: hieuonprem